CREATE TABLE users (
    userID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    username NVARCHAR(100) NOT NULL,
    name NVARCHAR(100) NOT NULL,
    passhash NVARCHAR(255) NOT NULL
);
GO 

CREATE TABLE libraries (
    libraryID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    libraryName NVARCHAR(100) NOT NULL,
    libraryAddress NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE books (
    bookID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    bookName NVARCHAR(255) NOT NULL,
    bookAddition NVARCHAR(50) DEFAULT 'Unkown',
    author NVARCHAR(100) DEFAULT 'unkown',
    filePath NVARCHAR(255),
    FK_libraryID INT FOREIGN KEY REFERENCES libraries(libraryID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
GO